### ISSUE TITLE
perpetual

### ISSUE THREAD

**Issue by bahram2000** [imanmousaei/coinexpy#6]
سلام واقعا خوب و تمیز نوشتید و دیدنش لذتبخشه
 من هرچی گشتم توی داکیومنت کوینکس چیزی در باره معامله به صورت بجز اسپوت نداشت
شما که بیشتر مطالعه کردید چیزی دیدید که بشه معامله به شکل
perpetual
 انجام داد؟

**Comment by imanmousaei** [comment]
Hello.
Yes, the perpetual doc is minimal but it can be found [here](https://github.com/coinexcom/coinex_perpetual_api/blob/master/perpetual_http_api.md).
I was gonna add Perpetual Trading in the next updates but I've been busy.
But you can always submit a pull request if you like.
Also, I would appreciate it if you'd write in English because Github is international.
Thank you

**Comment by imanmousaei** [comment]
سلام. ممنون از شما. بله داک perpetual یکم مینیماله. در این لینک هستش:
https://github.com/coinexcom/coinex_perpetual_api/blob/master/perpetual_http_api.md
قراره تو آپدیت های بعدی perpetual هم اضافه کنم ولی کار ریخته سرم فعلا وقت
نکردم. اگر خواستید میتونید pull request بدین که خیلی ممنون میشم.
